#!/bin/bash

pandoc resume.md -o index.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header.html \
  --include-after-body=_pandoc/footer.html \
  --variable="pagetitle:Resume :: Jack Senechal"

pandoc resume.md -o resume.odt --reference-doc=_pandoc/reference.odt

libreoffice --headless --convert-to doc resume.odt
libreoffice --headless --convert-to pdf resume.odt
