#!/bin/bash

pandoc resume.md -o index.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header.html \
  --include-after-body=_pandoc/footer.html \
  --variable="pagetitle:Resume :: Jack Senechal"

google-chrome-stable --headless --disable-gpu --no-pdf-header-footer --print-to-pdf=resume.pdf index.html
